spring:
  application:
    name: webzaim
  datasource:
    url: jdbc:postgresql://localhost:5432/your_database
    username: your_username
    password: your_password
  jpa:
    hibernate:
      ddl-auto: update
  liquibase:
      change-log: classpath:db/changelog/db.changelog-master.xml
