spring:
  application:
    name: Web-Zaim
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
  liquibase:
      change-log: classpath:db/changelog/db.changelog-master.yaml